# ONDA Badges Dakhla Configuration
app.name=ONDA Badges Dakhla

# Default Excel File Path
excel.default.path=C:/ONDA/tableau_des_badges(stage).xlsx

# Reminder Threshold (in days)
reminder.threshold.days=1
